baseURL = "http://alessiorapini.me/"
languageCode = "en-us"
title = "Alessio Rapini - Full Stack Designer"
copyright = "2017 Alessio Rapini"

[Author]
  name = "Alessio Rapini"
  role = "Full Stack Designer"
  mail = "hello@alessiorapini.me"
  github = "rub"

[params]
  description = "Alessio Rapini - Full Stack Designer"
