baseURL = "http://alessiorapini.me/"
languageCode = "en-us"
title = "Alessio Rapini - Product Designer"
copyright = "2018 Alessio Rapini"

[Author]
  name = "Alessio Rapini"
  role = "Product Designer"
  mail = "hello@alessiorapini.me"
  github = "rub"

[params]
  description = "Alessio Rapini - Product Designer (who codes too)"
